plugins {
    id 'java'
    id 'org.springframework.boot' version '3.4.1'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.ed'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
    avroTools
}

repositories {
    mavenCentral()
    maven {
        url = uri("https://packages.confluent.io/maven")
    }
}

dependencies {
    // Spring Boot Starters
    implementation "org.springframework.boot:spring-boot-starter-actuator:${springBootVersion}"
    implementation "io.micrometer:micrometer-registry-prometheus:${prometheusVersion}"

    implementation "org.springframework.boot:spring-boot-starter-web:${springBootVersion}"
    implementation "org.springframework.boot:spring-boot-starter-validation:${springBootVersion}"

    // Eureka
    implementation "org.springframework.cloud:spring-cloud-starter-netflix-eureka-client:${springCloudVersion}"

    // DevTools
    compileOnly "org.projectlombok:lombok:${lombokVersion}"
    annotationProcessor "org.projectlombok:lombok:${lombokVersion}"

    // Database
    implementation "org.springframework.boot:spring-boot-starter-data-jpa:${springBootVersion}"
    runtimeOnly "com.mysql:mysql-connector-j:${mysqlConnectorVersion}"

    // Mapper
    implementation "org.mapstruct:mapstruct:${mapstructVersion}"
    annotationProcessor "org.mapstruct:mapstruct-processor:${mapstructVersion}"

    // Test
    testImplementation "org.springframework.boot:spring-boot-starter-test:${springBootVersion}"
    testRuntimeOnly "org.junit.platform:junit-platform-launcher:${junitPlatformVersion}"

    // Feign
    implementation "org.springframework.cloud:spring-cloud-starter-openfeign:${springCloudVersion}"

    // Redis
    implementation "org.springframework.boot:spring-boot-starter-data-redis-reactive:${springRedisVersion}"

    //Kafka
    implementation "org.springframework.kafka:spring-kafka:${springKafkaVersion}"
    testImplementation "org.springframework.kafka:spring-kafka-test:${springKafkaVersion}"
    avroTools "org.apache.avro:avro-tools:${avroToolsVersion}"
    implementation "io.confluent:kafka-avro-serializer:${kafkaAvroSerializerVersion}"
    implementation "com.google.code.gson:gson:${gsonVersion}"
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
    }
}

tasks.named('test') {
    useJUnitPlatform()
}

tasks.withType(JavaCompile) {
    options.compilerArgs.add('-parameters')
}

sourceSets {
    main {
        java {
            srcDir 'build/generated-src'
        }
    }
}


tasks.register("generateAvroJava", JavaExec) {
    group = "build"
    description = "Compiles Avro schemas into Java classes"
    mainClass.set("org.apache.avro.tool.Main")
    classpath = configurations.avroTools
    args = [
            "compile", "-string", "schema",
            "src/main/avro/event_coupon_create_request_v1.avsc",
            "build/generated-src"
    ]
}

tasks.named("compileJava") {
    dependsOn("generateAvroJava")
}
