DROP TABLE IF EXISTS ED_COUPON_STATUS_CHANGE_LOG;
DROP TABLE IF EXISTS ED_COUPON;
DROP TABLE IF EXISTS ED_COUPON_TEMPLATE;

CREATE TABLE ED_COUPON_TEMPLATE
(
    COUPON_TEMPLATE_ID        BIGINT           NOT NULL AUTO_INCREMENT,
    COUPON_NAME               VARCHAR(255)     NOT NULL,
    COUPON_TEMPLATE_PUBLIC_ID VARCHAR(36)      NOT NULL,
    COUPON_ISSUANCE_TYPE      VARCHAR(255)     NOT NULL,
    COUPON_ISSUER_TYPE        VARCHAR(255)     NOT NULL,
    COUPON_ISSUER_ID          VARCHAR(36)      NULL,
    COUPON_USAGE_TARGET_TYPE  VARCHAR(255)     NOT NULL,
    COUPON_USAGE_TARGET_ID    VARCHAR(36)      NULL,
    DISCOUNT_TYPE             VARCHAR(255)     NOT NULL,
    DISCOUNT_VALUE            DECIMAL(10, 2)   NOT NULL,
    IS_ISSUABLE               BIT(1)           NOT NULL,
    EXPIRATION_DAYS           BIGINT           NULL,
    FIXED_EXPIRATION_DATE     TIMESTAMP        NULL,
    MAX_ISSUANCE              INT              NULL,
    IS_DELETED                BIT(1) DEFAULT 0 NULL,
    CREATED_AT                TIMESTAMP        NULL,
    CREATED_BY                VARCHAR(36)      NULL,
    UPDATED_AT                TIMESTAMP        NULL,
    UPDATED_BY                VARCHAR(36)      NULL,
    DELETED_AT                TIMESTAMP        NULL,
    DELETED_BY                VARCHAR(36)      NULL,
    CONSTRAINT pk_ed_coupon_template PRIMARY KEY (COUPON_TEMPLATE_ID)
);

CREATE TABLE ED_COUPON
(
    COUPON_ID          BIGINT           NOT NULL AUTO_INCREMENT,
    COUPON_TEMPLATE_ID VARCHAR(36)      NOT NULL,
    COUPON_PUBLIC_ID   VARCHAR(36)      NOT NULL,
    USER_ID            VARCHAR(36)      NULL,
    COUPON_STATE       VARCHAR(255)     NOT NULL,
    EXPIRATION_DATE    TIMESTAMP        NOT NULL,
    ISSUED_AT          TIMESTAMP        NOT NULL,
    IS_DELETED         BIT(1) DEFAULT 0 NULL,
    CREATED_AT         TIMESTAMP        NULL,
    CREATED_BY         VARCHAR(36)      NULL,
    UPDATED_AT         TIMESTAMP        NULL,
    UPDATED_BY         VARCHAR(36)      NULL,
    DELETED_AT         TIMESTAMP        NULL,
    DELETED_BY         VARCHAR(36)      NULL,
    CONSTRAINT PK_ED_COUPON PRIMARY KEY (COUPON_ID)
);

CREATE TABLE ED_COUPON_STATUS_CHANGE_LOG
(
    COUPON_STATUS_CHANGE_LOG_ID BIGINT           NOT NULL AUTO_INCREMENT,
    BEFORE_STATUS               VARCHAR(255)     NOT NULL,
    AFTER_STATUS                VARCHAR(255)     NOT NULL,
    REASON                      VARCHAR(255)     NOT NULL,
    CHANGED_AT                  TIMESTAMP        NOT NULL,
    ORDER_ID                    VARCHAR(18)      NULL,
    COUPON_ID                   BIGINT           NOT NULL,
    IS_DELETED                  BIT(1) DEFAULT 0 NULL,
    CREATED_AT                  TIMESTAMP        NULL,
    CREATED_BY                  VARCHAR(36)      NULL,
    UPDATED_AT                  TIMESTAMP        NULL,
    UPDATED_BY                  VARCHAR(36)      NULL,
    DELETED_AT                  TIMESTAMP        NULL,
    DELETED_BY                  VARCHAR(36)      NULL,
    CONSTRAINT PK_ED_COUPON_STATUS_CHANGE_LOG PRIMARY KEY (COUPON_STATUS_CHANGE_LOG_ID)
);

ALTER TABLE ED_COUPON
    ADD CONSTRAINT UC_ED_COUPON_PUBLIC_ID UNIQUE (COUPON_PUBLIC_ID);

ALTER TABLE ED_COUPON_TEMPLATE
    ADD CONSTRAINT UC_ED_COUPON_TEMPLATE_PUBLIC_ID UNIQUE (COUPON_TEMPLATE_PUBLIC_ID);
