version: '3.8'

services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass password123
    volumes:
      - redis_data:/data
    networks:
      - be-network

volumes:
  mysql_data:
  redis_data:

networks:
  be-network:
    driver: bridge