#Spring
springBootVersion=3.4.1
springCloudVersion=4.2.0
lombokVersion=1.18.36
mysqlConnectorVersion=9.1.0
junitPlatformVersion=1.11.4
#Docs
springRestdocsVersion=3.0.3
springdocOpenapiVersion=2.7.0
restdocsApiSpecVersion=0.19.2
#Kafka
springKafkaVersion=3.3.1
avroToolsVersion=1.12.0
kafkaAvroSerializerVersion=7.8.0
gsonVersion=2.11.0
# Prometheus
prometheusVersion=1.14.2
