### Create a new order
POST http://localhost:19091/api/v1/orders
Content-Type: application/json
X-User-Id: 550e8400-e29b-41d4-a716-446655440006

{
  "orderer": {
    "name": "홍길동",
    "phoneNumber": "010-1234-5678"
  },
  "orderItemDtos": [
    {
      "brandId": "33732dd3-3901-4429-ba58-676c6965923",
      "productId": "e4030362-0251-441a-b752-63feea51337c",
      "productName": "베이직 긴팔 티셔츠",
      "quantity": 1,
      "unitPrice": 40000,
      "size": "L",
      "productCategory": "TOP",
      "orderItemCouponId": null
    },
    {
      "brandId": "55732dd3-3901-4429-ba58-676c6965923",
      "productId": "37eede74-184e-404e-a4f6-b1c063d91795",
      "productName": "스웻 팬츠",
      "quantity": 1,
      "unitPrice": 50000,
      "size": "L",
      "productCategory": "BOTTOM",
      "orderItemCouponId": null
    }
  ],
  "orderDeliveryRequest": {
    "receiverName": "김철수",
    "receiverAddress": "서울시 강남구 테헤란 123",
    "receiverPhoneNumber": "02-907-6543",
    "receiverMobileNumber": "010-9076-5432",
    "zipcode": "06234",
    "roadZipCode": "06234",
    "requirement": "부재시 경비실에 맡겨주세요"
  }
}
