spring:
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        default_schema: public
        default_batch_fetch_size: 500

    show-sql: true
    open-in-view: false

  batch:
    jdbc:
      initialize-schema: never

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  kafka:
    bootstrap-servers: ${KAFKA_SERVERS}
    schema-registry-url: ${DEV_SCHEMA_REGISTRY_URL}
    consumer:
      group-id: ${CONSUMER_GROUP_ID}

pg:
  tosspayments:
    secret-key: ${TOSS_PAYMENTS_SECRET_KEY}
    base-url: ${TOSS_PAYMENTS_BASE_URL}