spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        default_schema: public
        default_batch_fetch_size: 500
    open-in-view: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/product?useSSL=false&
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

  kafka:
    bootstrap-servers: ${KAFKA_SERVERS}
    schema-registry-url: ${PROD_SCHEMA_REGISTRY_URL}
    consumer:
      group-id: ${CONSUMER_GROUP_ID}

pg:
  tosspayments:
    secret-key: ${TOSS_PAYMENTS_SECRET_KEY}
    base-url: ${TOSS_PAYMENTS_BASE_URL}

management:
  endpoints:
    web:
      exposure:
        include: prometheus
      base-path: ${ACTUATOR_BASE_PATH}
    jmx:
      exposure:
        exclude: "*"
    access:
      default: none
  prometheus:
    metrics:
      export:
        enabled: true
  endpoint:
    prometheus:
      access: unrestricted
  server:
    address: ${MANAGEMENT_SERVER_ADDRESS}
    port: ${MANAGEMENT_SERVER_PORT}
