DROP TABLE if EXISTS ED_PAYMENT;
DROP TABLE if EXISTS ED_PAYMENT_HISTORY;

CREATE TABLE `ED_PAYMENT`
(
    `PAYMENT_ID`                BIGINT       NOT NULL AUTO_INCREMENT,
    `PAYMENT_PUBLIC_ID`         VARCHAR(36)  DEFAULT NULL,
    `PAYMENT_KEY`               VARCHAR(200) DEFAULT NULL,
    `IDEMPOTENCY_KEY`           VARCHAR(36)  DEFAULT NULL,
    `USER_PUBLIC_ID`            VARCHAR(36)  NOT NULL,
    `PAYMENT_STATUS`            ENUM('READY','VERIFY_FAILED', 'DONE', 'PARTIAL_CANCELED', 'CANCELED', 'ABORTED') NOT NULL,
    `ORDER_PUBLIC_ID`           CHAR(18)     NOT NULL,
    `ORDER_NAME`                VARCHAR(255) NOT NULL,
    `TOTAL_AMOUNT`              BIGINT       DEFAULT NULL,
    `BALANCE_AMOUNT`            BIGINT       DEFAULT NULL,
    `CONFIRM_DEADLINE`          TIMESTAMP    NOT NULL,
    `CANCEL_DEADLINE`           TIMESTAMP    NOT NULL,
    `CREATED_AT`                TIMESTAMP    NOT NULL,
    `CREATED_BY`                VARCHAR(36)  DEFAULT NULL,
    `UPDATED_AT`                TIMESTAMP    DEFAULT NULL,
    `UPDATED_BY`                VARCHAR(36)  DEFAULT NULL,
    `DELETED_AT`                TIMESTAMP    DEFAULT NULL,
    `DELETED_BY`                VARCHAR(36)  DEFAULT NULL,
    `IS_DELETED`                BIT(1)       NOT NULL,
    PRIMARY KEY (`PAYMENT_ID`),
    UNIQUE KEY `UKMBQSCLI8W5457J9WLLJ1IJP30` (`PAYMENT_PUBLIC_ID`),
    UNIQUE KEY `UK2M21C5PKJISKFQHNXSL3U5L3V` (`PAYMENT_KEY`),
    UNIQUE KEY `UKDM29Y305P71XAP9LQ3UITWI25` (`ORDER_PUBLIC_ID`)
) ENGINE=INNODB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `ED_PAYMENT_HISTORY`
(
    `PAYMENT_HISTORY_ID`        BIGINT      NOT NULL AUTO_INCREMENT,
    `PAYMENT_HISTORY_PUBLIC_ID` VARCHAR(36) NOT NULL,
    `PAYMENT_ID`                BIGINT      NOT NULL,
    `LAST_TRANSACTION_KEY`      VARCHAR(36)  DEFAULT NULL,
    `PAYMENT_STATUS`            ENUM('READY','VERIFY_FAILED', 'DONE', 'PARTIAL_CANCELED', 'CANCELED', 'ABORTED') NOT NULL,
    `TOTAL_AMOUNT`              BIGINT       DEFAULT NULL,
    `BALANCE_AMOUNT`            BIGINT       DEFAULT NULL,
    `CANCEL_AMOUNT`             BIGINT       DEFAULT NULL,
    `CANCEL_REASON`             VARCHAR(255) DEFAULT NULL,
    `CREATED_AT`                TIMESTAMP   NOT NULL,
    `UPDATED_AT`                TIMESTAMP    DEFAULT NULL,
    `DELETED_AT`                TIMESTAMP    DEFAULT NULL,
    `IS_DELETED`                BIT(1)      NOT NULL,
    PRIMARY KEY (`PAYMENT_HISTORY_ID`),
    UNIQUE KEY `UK9T6O3DCIN5TSFFKR69GIINPO5` (`PAYMENT_HISTORY_PUBLIC_ID`)
) ENGINE=INNODB AUTO_INCREMENT=14 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;