{
  "type": "record",
  "name": "OrderPaymentCancelRequest",
  "namespace": "com.ed",
  "fields": [
    {
      "name": "userId",
      "type": "string"
    },
    {
      "name": "orderId",
      "type": "string"
    },
    {
      "name": "paymentId",
      "type": "string"
    },
    {
      "name": "cancelAmount",
      "type": "long"
    },
    {
      "name": "cancelReason",
      "type": "string"
    },
    {
      "name": "requestDateTime",
      "type": {
        "type": "long",
        "logicalType": "local-timestamp-millis"
      }
    }
  ]
}