{
  "type": "record",
  "name": "OrderPaymentCreateRequest",
  "namespace": "com.ed",
  "fields": [
    {
      "name": "userId",
      "type": "string"
    },
    {
      "name": "orderId",
      "type": "string"
    },
    {
      "name": "orderName",
      "type": "string"
    },
    {
      "name": "paymentDeadline",
      "type": {
        "type": "long",
        "logicalType": "local-timestamp-millis"
      }
    },
    {
      "name": "orderCancelDeadline",
      "type": {
        "type": "long",
        "logicalType": "local-timestamp-millis"
      }
    },
    {
      "name": "totalAmount",
      "type": "long"
    },
    {
      "name": "messageTimestamp",
      "type": {
        "type": "long",
        "logicalType": "local-timestamp-millis"
      }
    }
  ]
}