{
  "type": "record",
  "name": "OrderPaymentCancelResponse",
  "namespace": "com.ed",
  "fields": [
    {
      "name": "isSuccess",
      "type": "boolean"
    },
    {
      "name": "orderId",
      "type": "string"
    },
    {
      "name": "paymentId",
      "type": "string"
    },
    {
      "name": "cancelAmount",
      "type": "long"
    },
    {
      "name": "balanceAmount",
      "type": "long"
    },
    {
      "name": "messageTimestamp",
      "type": {
        "type": "long",
        "logicalType": "local-timestamp-millis"
      }
    }
  ]
}