{"type":"record","name":"OrderPaymentCreateRequest","namespace":"com.ed","fields":[{"name":"userId","type":{"type":"string","avro.java.string":"String"}},{"name":"orderId","type":{"type":"string","avro.java.string":"String"}},{"name":"orderName","type":{"type":"string","avro.java.string":"String"}},{"name":"paymentDeadline","type":{"type":"long","logicalType":"local-timestamp-millis"}},{"name":"orderCancelDeadline","type":{"type":"long","logicalType":"local-timestamp-millis"}},{"name":"totalAmount","type":"long"},{"name":"messageTimestamp","type":{"type":"long","logicalType":"local-timestamp-millis"}}]}