{"type":"record","name":"OrderPaymentCancelRequest","namespace":"com.ed","fields":[{"name":"userId","type":{"type":"string","avro.java.string":"String"}},{"name":"orderId","type":{"type":"string","avro.java.string":"String"}},{"name":"paymentId","type":{"type":"string","avro.java.string":"String"}},{"name":"cancelAmount","type":"long"},{"name":"cancelReason","type":{"type":"string","avro.java.string":"String"}},{"name":"requestDateTime","type":{"type":"long","logicalType":"local-timestamp-millis"}}]}