spring:
  application:
    name: product-service
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  elasticsearch:
    host: ${ELASTIC_HOST}
    username: ${ELASTIC_USERNAME}
    password: ${ELASTIC_PASSWORD}
    repositories:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    open-in-view: false

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}

server:
  port: 19093

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE}

management:
  endpoints:
    web:
      exposure:
        include: prometheus
      base-path: ${ACTUATOR_BASE_PATH}
    jmx:
      exposure:
        exclude: "*"
    access:
      default: none
  prometheus:
    metrics:
      export:
        enabled: true
  endpoint:
    prometheus:
      access: unrestricted
  server:
    address: ${MANAGEMENT_SERVER_ADDRESS}
    port: ${MANAGEMENT_SERVER_PORT}
