@jwttoken = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJhdXRoLXNlcnZpY2UiLCJpYXQiOjE3MzYyNDM0OTQsImV4cCI6MTgyMjY0MzQ5NCwidXNlcklkIjoiZDFhMzU0ZDMtMWQ1Yi00YzE3LWI3MjctOGIzNTFjOWRhZTYzIiwidXNlclJvbGUiOiJERUZBVUxUX0NVU1RPTUVSIn0.VViuBe3YMyCg5asIPec2jc-Nd6Wkd9Co-25XFEI-NbYiJKEZK5UH8kCb1phPvBZptpGCXzkYV7ZGYCmPcYS7vw"
POST http://localhost:19096/api/v1/coupons/templates
Content-Type: application/json
Authorization: "Bearer {{jwttoken}}"

{
  "couponName": "string",
  "couponIssuanceType": "MANUAL",
  "couponIssuerType": "SERVICE",
  "maxIssuance": 0,
  "couponUsageTargetType": "ALL",
  "discountType": "PERCENTAGE",
  "discountValue": 10.5,
  "expirationDays": 1,
  "expirationDate": "2021-08-31T14:00:00.000Z"
}