DROP TABLE IF EXISTS `ED_EVENT_USER`;
DROP TABLE IF EXISTS `ED_EVENT`;

CREATE TABLE `ED_EVENT`
(
    `IS_DELETED`           BIT(1)      DEFAULT B'0',
    `CREATED_AT`           TIMESTAMP   DEFAULT NULL,
    `CURRENT_PARTICIPANTS` BIGINT              NOT NULL,
    `DELETED_AT`           TIMESTAMP   DEFAULT NULL,
    `EVENT_END_AT`         TIMESTAMP           NOT NULL,
    `EVENT_START_AT`       TIMESTAMP           NOT NULL,
    `MAX_PARTICIPANTS`     BIGINT              NOT NULL,
    `UPDATED_AT`           TIMESTAMP   DEFAULT NULL,
    `ID`                   BIGINT              NOT NULL AUTO_INCREMENT,
    `COUPON_TEMPLATE_ID`   VARCHAR(36)         NOT NULL,
    `CREATED_BY`           VARCHAR(36) DEFAULT NULL,
    `DELETED_BY`           VARCHAR(36) DEFAULT NULL,
    `EVENT_PUBLIC_ID`      VARCHAR(36)         NOT NULL,
    `UPDATED_BY`           VARCHAR(36) DEFAULT NULL,
    `EVENT_NAME`           VARCHAR(50)         NOT NULL,
    `EVENT_TYPE`           ENUM ('RUSH_EVENT') NOT NULL,
    CONSTRAINT PK_ED_EVENT PRIMARY KEY (`ID`)
);

CREATE TABLE `ED_EVENT_USER`
(
    `IS_DELETED` BIT(1)      DEFAULT B'0',
    `CREATED_AT` TIMESTAMP   DEFAULT NULL,
    `DELETED_AT` TIMESTAMP   DEFAULT NULL,
    `UPDATED_AT` TIMESTAMP   DEFAULT NULL,
    `ID`         BIGINT       NOT NULL AUTO_INCREMENT,
    `CREATED_BY` VARCHAR(36) DEFAULT NULL,
    `DELETED_BY` VARCHAR(36) DEFAULT NULL,
    `UPDATED_BY` VARCHAR(36) DEFAULT NULL,
    `EVENT_ID`   VARCHAR(255) NOT NULL,
    `USER_ID`    VARCHAR(255) NOT NULL,
    CONSTRAINT PK_ED_EVENT_USER PRIMARY KEY (`ID`)
);

ALTER TABLE ED_EVENT
    ADD CONSTRAINT UC_ED_PUBLIC_ID UNIQUE (`EVENT_PUBLIC_ID`);

ALTER TABLE ED_EVENT_USER
    ADD INDEX IDX_EVENT_ID_USER_ID (`EVENT_ID`, `USER_ID`);
